name: "Content Proposal"
description: "Propose new documentation topics or articles"
labels: ["content proposal", "needs forum discussion", "triage needed"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for proposing new Swift documentation!

        For significant new content, please consider starting a discussion on the
        [Swift Forums](https://forums.swift.org/c/development/swift-docc/80) first.

        See our [Contributing Guide](https://github.com/swiftlang/docs/blob/main/CONTRIBUTING.md)
        for guidance on proposing larger content additions.

  - type: dropdown
    id: package
    attributes:
      label: "Target Package"
      description: "Which package should contain this new content?"
      options:
        - API Guidelines
        - Language Guides
        - Server Guides
        - Ecosystem Tools
        - New package needed
        - Not sure
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: "Proposal"
      description: "What should this new documentation cover and why is it needed?"
      placeholder: "Describe the proposed content, what problem it solves, and what audience would benefit"
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: "Scope and Outline"
      description: "What topics should be covered? (optional outline)"
      placeholder: |
        - Topic 1
        - Topic 2
        - Examples needed
    validations:
      required: false
