name: "Task"
description: "Track internal work or maintenance tasks"
labels: ["task", "triage needed"]
body:
  - type: markdown
    attributes:
      value: |
        Tasks track internal work items including:
        - Build system or tooling updates
        - Documentation infrastructure improvements
        - Multi-step work that needs coordination

        For content changes, consider using Content Error, Enhancement, or Content Proposal templates.

  - type: dropdown
    id: package
    attributes:
      label: "Affected Collection(s)"
      description: "Which collections does this task affect?"
      multiple: true
      options:
        - API Guidelines
        - Language Guides
        - Server Guides
        - Ecosystem Tools
        - Repository infrastructure
        - All collections
    validations:
      required: true

  - type: dropdown
    id: task_type
    attributes:
      label: "Task Type"
      description: "What kind of task is this?"
      options:
        - Build system update
        - Tooling improvement
        - Infrastructure maintenance
        - Process improvement
        - Coordination / umbrella issue
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear description of the task"
      placeholder: "Describe what needs to be done and why"
    validations:
      required: true

